kind: pipeline
name: default

steps:
  - name: package
    image: maven:openjdk
    volumes:
      - name: maven-build
        path: /app
    commands:
      - mvn clean package
      - cp target/springboot-0.0.1-SNAPSHOT.jar /app/springboot-0.0.1-SNAPSHOT.jar
      - cp Dockerfile /app/Dockerfile
      - cp buildrun.sh /app/buildrun.sh
      
  - name: build
    image: appleboy/drone-ssh
    setting: 
      host: drone-server
      username: root
      password:
        from_secret: 10.199_SSH_KEY
      port: 22
      script:
        - cd /app
        - ./buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
