kind: pipeline
name: default

steps:    
  - name: build
    image: appleboy/drone-ssh:1.6.3
    setting: 
      host: 192.168.10.199
      username: root
      user: root
      password:
        from_secret: 10.199_SSH_KEY
      port: 22
      script:
        - cd /app
        - ./buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
