kind: pipeline
name: default

steps:
- name: test
  image: maven:openjdk
  volumes:
  -name: maven-build
  path: /app
  commands:
  - mvn clean package
  - cp target/springboot-0.0.1-SNAPSHOT.jar /app/springboot-0.0.1-SNAPSHOT.jar
  - cp Dockerfile /app/Dockerfile
  - cp buildrun.sh /app/buildrun.sh
