kind: pipeline
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: drone-server
    username: 
      from_secret: 10.199_SSH_USER
    key: 
      from_secret: 10.199_SSH_KEY
    port: 22
    script:
      - cd /app
      - sh buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
