kind: pipeline
name: default

steps:    
  - name: build
    image: appleboy/drone-ssh
    pull: true
    secrets: [ 10.199_SSH_USER,10.199_SSH_PWD ]
    host: 192.168.10.199
    port: 22
    command_timeout: 180
    script:
      - cd /app
      - ./buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
