kind: pipeline
name: default

steps:
  - name: build_&_run
    image: appleboy/drone-ssh
    settings:
      host: 192.168.10.199
      username: root
      password: 
        from_secret: 10.199_SSH_PWD
      port: 22 
      command_timeout: 180m
      script:
        - cd /app
        - sh buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
