kind: pipeline
name: default

steps:
  - name: prepare
    image: appleboy/drone-ssh
    settings:
      host: 192.168.10.199
      username: root
      password: 
        from_secret: 10.199_SSH_PWD
      port: 22 
      command_timeout: 180m
      script:
        - cd /app
        - rm -rf *
  
  - name: package
    image: maven:openjdk
    volumes:
      - name: maven-build
        path: /app
    commands:
      - mvn clean package
      - cp target/springboot-0.0.1-SNAPSHOT.jar /app/springboot-0.0.1-SNAPSHOT.jar
      - cp Dockerfile /app/Dockerfile
      - cp buildrun.sh /app/buildrun.sh
  
  - name: build_&_run
    image: appleboy/drone-ssh
    settings:
      host: 192.168.10.199
      username: root
      password: 
        from_secret: 10.199_SSH_PWD
      port: 22 
      command_timeout: 180m
      script:
        - cd /app
        - sh buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
