kind: pipeline
name: default

steps:    
  - name: build
    image: appleboy/drone-ssh
    username: root
    password: 1qaz2wsx
    host: drone-server
    port: 22
    command_timeout: 180
    script:
      - cd /app
      - ./buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
