kind: pipeline
type: docker
name: springboot_test_drone

step:
  - name: package
    image: maven:openjdk
    volumes:
      - name: maven-cache
        path: /root/.m2
      - name: maven-build
        path: /app/build
    command:
      - mvn clean package
      - cp target/springboot-1.0.0-SNAPSHOT.jar /app/build/springboot-1.0.0-SNAPSHOT.jar
      - cp Dockerfile /app/build/Dockerfile
      - cp buildrun.sh /app/build/buildrun.sh
    script:
      - ./buildrun.sh 
