kind: pipeline
name: default

steps:    
  - name: build
    image: appleboy/drone-ssh
    username: root
    password: 1qaz2wsx
    host: drone-server
    port: 22
    command_timeout: 180
    volumes:
      -name: key_path
       key_path: /root/.ssh/id_rsa.pub
    script:
      - cd /app
      - ./buildrun.sh
volumes: 
  - name: maven-build
    host: 
      path: /app 
  - name: key_path
    host:
      path: /root/.ssh/id_rsa.pub
